<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PasienSeeder extends Seeder
{
    public function run()
    {
        $this->db->table('pasien')->insertBatch([
            [
                'no_rm' => 'RM001',
                'nama' => 'John Doe',
                'perusahaan' => 'PT ABC',
                'nik' => '1234567890123456',
                'departemen' => 'Produksi',
                'bagian' => 'Assembly',
                'usia' => 30,
                'tgl_mcu' => '2025-01-01',
            ],
            [
                'no_rm' => 'RM002',
                'nama' => 'Jane Smith',
                'perusahaan' => 'PT XYZ',
                'nik' => '1234567890123457',
                'departemen' => 'Keuangan',
                'bagian' => 'Akuntansi',
                'usia' => 28,
                'tgl_mcu' => '2025-01-02',
            ],
            [
                'no_rm' => 'RM003',
                'nama' => 'Robert Brown',
                'perusahaan' => 'PT DEF',
                'nik' => '1234567890123458',
                'departemen' => 'HRD',
                'bagian' => 'Rekrutmen',
                'usia' => 35,
                'tgl_mcu' => '2025-01-03',
            ],
            [
                'no_rm' => 'RM004',
                'nama' => 'Emily Davis',
                'perusahaan' => 'PT GHI',
                'nik' => '1234567890123459',
                'departemen' => 'IT',
                'bagian' => 'Support',
                'usia' => 25,
                'tgl_mcu' => '2025-01-04',
            ],
            [
                'no_rm' => 'RM005',
                'nama' => 'Michael Wilson',
                'perusahaan' => 'PT JKL',
                'nik' => '1234567890123460',
                'departemen' => 'Logistik',
                'bagian' => 'Pengiriman',
                'usia' => 32,
                'tgl_mcu' => '2025-01-05',
            ],
            [
                'no_rm' => 'RM006',
                'nama' => 'Sarah Moore',
                'perusahaan' => 'PT MNO',
                'nik' => '1234567890123461',
                'departemen' => 'Marketing',
                'bagian' => 'Promosi',
                'usia' => 27,
                'tgl_mcu' => '2025-01-06',
            ],
            [
                'no_rm' => 'RM007',
                'nama' => 'Daniel Taylor',
                'perusahaan' => 'PT PQR',
                'nik' => '1234567890123462',
                'departemen' => 'Produksi',
                'bagian' => 'Packing',
                'usia' => 29,
                'tgl_mcu' => '2025-01-07',
            ],
            [
                'no_rm' => 'RM008',
                'nama' => 'Jessica Lee',
                'perusahaan' => 'PT STU',
                'nik' => '1234567890123463',
                'departemen' => 'Keuangan',
                'bagian' => 'Perencanaan',
                'usia' => 31,
                'tgl_mcu' => '2025-01-08',
            ],
            [
                'no_rm' => 'RM009',
                'nama' => 'Andrew White',
                'perusahaan' => 'PT VWX',
                'nik' => '1234567890123464',
                'departemen' => 'R&D',
                'bagian' => 'Pengembangan',
                'usia' => 33,
                'tgl_mcu' => '2025-01-09',
            ],
            [
                'no_rm' => 'RM010',
                'nama' => 'Karen Thomas',
                'perusahaan' => 'PT YZA',
                'nik' => '1234567890123465',
                'departemen' => 'HRD',
                'bagian' => 'Pelatihan',
                'usia' => 26,
                'tgl_mcu' => '2025-01-10',
            ],
            [
                'no_rm' => 'RM011',
                'nama' => 'Kevin Martinez',
                'perusahaan' => 'PT BCD',
                'nik' => '1234567890123466',
                'departemen' => 'Produksi',
                'bagian' => 'Quality Control',
                'usia' => 34,
                'tgl_mcu' => '2025-01-11',
            ],
            [
                'no_rm' => 'RM012',
                'nama' => 'Laura Hernandez',
                'perusahaan' => 'PT EFG',
                'nik' => '1234567890123467',
                'departemen' => 'IT',
                'bagian' => 'Infrastruktur',
                'usia' => 24,
                'tgl_mcu' => '2025-01-12',
            ],
            [
                'no_rm' => 'RM013',
                'nama' => 'Chris Martin',
                'perusahaan' => 'PT HIJ',
                'nik' => '1234567890123468',
                'departemen' => 'Logistik',
                'bagian' => 'Penyimpanan',
                'usia' => 36,
                'tgl_mcu' => '2025-01-13',
            ],
            [
                'no_rm' => 'RM014',
                'nama' => 'Sophia Garcia',
                'perusahaan' => 'PT KLM',
                'nik' => '1234567890123469',
                'departemen' => 'Marketing',
                'bagian' => 'Distribusi',
                'usia' => 22,
                'tgl_mcu' => '2025-01-14',
            ],
            [
                'no_rm' => 'RM015',
                'nama' => 'Ryan Walker',
                'perusahaan' => 'PT NOP',
                'nik' => '1234567890123470',
                'departemen' => 'R&D',
                'bagian' => 'Desain Produk',
                'usia' => 28,
                'tgl_mcu' => '2025-01-15',
            ],
        ]);
    }
}
